name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker images
        run: docker-compose build
      - name: Test application
        run: docker-compose up -d
      - name: Check frontend
        run: curl http://localhost:81
      - name: Cleanup
        run: docker-compose down
