name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Paso 1: Detener el stack labjs2025
      - name: Stop labjs2025 stack
        shell: pwsh # Usar PowerShell explícitamente
        run: |
          try {
            docker-compose -p labjs2025 down
          } catch {
            Write-Output "No labjs2025 stack running"
          }
      
      # Paso 2: Eliminar imágenes específicas
      - name: Remove specific images
        shell: pwsh # Usar PowerShell explícitamente
        run: |
          try {
            docker rmi -f moby/buildkit labjs2025-backend labjs2025-frontend
          } catch {
            Write-Output "Some or all images not found"
          }
      
      - name: Build Docker images
        shell: pwsh
        run: docker-compose build
      
      - name: Test application
        shell: pwsh
        run: docker-compose up -d
      
      - name: Check frontend
        shell: pwsh
        run: curl http://localhost:81
      
      # Opcional: Limpiar después de la ejecución
      # - name: Cleanup
      #   shell: pwsh
      #   run: docker-compose down
